"""allow sources without an airbyte counterpart

Revision ID: 0a8fe214b2be
Revises: 65b80028f3f7
Create Date: 2026-09-05 21:07:04.241137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a8fe214b2be"
down_revision: Union[str, None] = "65b80028f3f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # batch_alter_table : SQLite ne sait pas relacher un NOT NULL en place, il
    # faut recreer la table. Le mode batch fonctionne aussi sur PostgreSQL, ou
    # il se traduit en simple ALTER COLUMN.
    with op.batch_alter_table("data_sources") as batch:
        batch.alter_column("airbyte_source_id", existing_type=sa.VARCHAR(length=64), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_sources") as batch:
        batch.alter_column("airbyte_source_id", existing_type=sa.VARCHAR(length=64), nullable=False)
    # ### end Alembic commands ###
