"""add questions

Revision ID: 0c025fb9ac96
Revises: 0a8fe214b2be
Create Date: 2026-09-05 22:24:14.789532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c025fb9ac96"
down_revision: Union[str, None] = "0a8fe214b2be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("texte", sa.Text(), nullable=False),
        sa.Column("reponse", sa.Text(), nullable=False),
        sa.Column("sql", sa.Text(), nullable=True),
        sa.Column("nb_lignes", sa.Integer(), nullable=True),
        sa.Column("resultat", sa.JSON(), nullable=True),
        sa.Column("etapes", sa.JSON(), nullable=False),
        sa.Column("cout_dollars", sa.Float(), nullable=False),
        sa.Column("jetons", sa.Integer(), nullable=False),
        sa.Column("duree_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cree_le", sa.DateTime(timezone=True), nullable=False),
        sa.Column("maj_le", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questions_organization_id"), "questions", ["organization_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_organization_id"), table_name="questions")
    op.drop_table("questions")
    # ### end Alembic commands ###
