"""dashboards, widgets and sync schedule

Revision ID: 0f8ea4758f0d
Revises: b31d8041d874
Create Date: 2026-09-06 00:31:18.138109

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f8ea4758f0d"
down_revision: Union[str, None] = "b31d8041d874"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboards",
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("nom", sa.String(length=120), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cree_le", sa.DateTime(timezone=True), nullable=False),
        sa.Column("maj_le", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dashboards_workspace_id"), "dashboards", ["workspace_id"], unique=False
    )
    op.create_table(
        "widgets",
        sa.Column("dashboard_id", sa.String(), nullable=False),
        sa.Column("question_id", sa.String(), nullable=True),
        sa.Column("titre", sa.String(length=120), nullable=False),
        sa.Column("sql", sa.Text(), nullable=False),
        sa.Column("graphique", sa.JSON(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cree_le", sa.DateTime(timezone=True), nullable=False),
        sa.Column("maj_le", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dashboard_id"],
            ["dashboards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_widgets_dashboard_id"), "widgets", ["dashboard_id"], unique=False)
    op.add_column(
        "data_sources",
        sa.Column("planification", sa.String(length=20), server_default="manuelle", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_sources", "planification")
    op.drop_index(op.f("ix_widgets_dashboard_id"), table_name="widgets")
    op.drop_table("widgets")
    op.drop_index(op.f("ix_dashboards_workspace_id"), table_name="dashboards")
    op.drop_table("dashboards")
    # ### end Alembic commands ###
