"""surveillances programmees

Revision ID: 20014085af7f
Revises: ff3a066fe009
Create Date: 2026-09-22 22:49:26.503938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20014085af7f'
down_revision: Union[str, None] = 'ff3a066fe009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveillances',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('titre', sa.String(length=120), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('declencheur', sa.Enum('ANOMALIE', 'SEUIL_DEPASSE', 'SEUIL_SOUS', 'TOUJOURS', name='declencheur', native_enum=False, length=20), nullable=False),
    sa.Column('seuil', sa.Float(), nullable=True),
    sa.Column('heure', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('derniere_execution', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dernier_etat', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('maj_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveillances_workspace_id'), 'surveillances', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surveillances_workspace_id'), table_name='surveillances')
    op.drop_table('surveillances')
    # ### end Alembic commands ###
