"""add data sources and organization destination

Revision ID: 32c08c6c0e68
Revises: 98ee3a0d2ef4
Create Date: 2026-09-05 16:43:03.163524

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32c08c6c0e68"
down_revision: Union[str, None] = "98ee3a0d2ef4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("nom", sa.String(length=255), nullable=False),
        sa.Column("type_source", sa.String(length=50), nullable=False),
        sa.Column(
            "statut",
            sa.Enum(
                "CONNECTEE",
                "SYNCHRONISATION",
                "PRETE",
                "ERREUR",
                name="statutsource",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("airbyte_source_id", sa.String(length=64), nullable=False),
        sa.Column("airbyte_connection_id", sa.String(length=64), nullable=True),
        sa.Column("schema_entrepot", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cree_le", sa.DateTime(timezone=True), nullable=False),
        sa.Column("maj_le", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "organizations", sa.Column("airbyte_destination_id", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "airbyte_destination_id")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
