"""reglages llm modifiables sans redeploiement

Revision ID: 38d49604f192
Revises: 20014085af7f
Create Date: 2026-09-22 23:01:48.866839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d49604f192'
down_revision: Union[str, None] = '20014085af7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reglages_llm',
    sa.Column('cle', sa.String(length=80), nullable=False),
    sa.Column('valeur', sa.Text(), server_default='', nullable=False),
    sa.Column('secret', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('maj_le', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reglages_llm_cle'), 'reglages_llm', ['cle'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reglages_llm_cle'), table_name='reglages_llm')
    op.drop_table('reglages_llm')
    # ### end Alembic commands ###
