"""glossaire metier sur le catalogue

Revision ID: 53f07859dc37
Revises: 8b47dd9d83a3
Create Date: 2026-09-22 22:40:37.041921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f07859dc37'
down_revision: Union[str, None] = '8b47dd9d83a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations_catalogue',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('table_nom', sa.String(length=200), nullable=False),
    sa.Column('colonne_nom', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('maj_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'table_nom', 'colonne_nom', name='uq_annotation_cible')
    )
    op.create_index(op.f('ix_annotations_catalogue_workspace_id'), 'annotations_catalogue', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotations_catalogue_workspace_id'), table_name='annotations_catalogue')
    op.drop_table('annotations_catalogue')
    # ### end Alembic commands ###
