"""prefix warehouse tables per source

Revision ID: 65b80028f3f7
Revises: 9c765b1b3bda
Create Date: 2026-09-05 18:26:54.466716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65b80028f3f7"
down_revision: Union[str, None] = "9c765b1b3bda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='' : SQLite refuse une colonne NOT NULL sans defaut cote
    # base. Les sources deja creees gardent des tables sans prefixe, ce qui est
    # exactement le comportement qu'on veut pour elles.
    op.add_column(
        "data_sources",
        sa.Column("prefixe_entrepot", sa.String(length=32), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_sources", "prefixe_entrepot")
    # ### end Alembic commands ###
