"""audit log, notifications, feedback and explanation

Revision ID: 8b47dd9d83a3
Revises: 0f8ea4758f0d
Create Date: 2026-09-06 00:44:36.759584

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b47dd9d83a3"
down_revision: Union[str, None] = "0f8ea4758f0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("titre", sa.String(length=160), nullable=False),
        sa.Column("corps", sa.Text(), nullable=False),
        sa.Column("lien", sa.String(length=255), nullable=True),
        sa.Column("lue", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cree_le", sa.DateTime(timezone=True), nullable=False),
        sa.Column("maj_le", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_lue"), "notifications", ["lue"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("cible_type", sa.String(length=40), nullable=False),
        sa.Column("cible_id", sa.String(length=64), nullable=True),
        sa.Column("cible_nom", sa.String(length=255), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cree_le", sa.DateTime(timezone=True), nullable=False),
        sa.Column("maj_le", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_organization_id"), "audit_logs", ["organization_id"], unique=False
    )
    op.add_column(
        "questions", sa.Column("explication", sa.Text(), server_default="", nullable=False)
    )
    op.add_column("questions", sa.Column("avis", sa.Integer(), nullable=True))
    op.add_column(
        "questions", sa.Column("commentaire_avis", sa.Text(), server_default="", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "commentaire_avis")
    op.drop_column("questions", "avis")
    op.drop_column("questions", "explication")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_lue"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
