"""persist discovered and selected streams

Revision ID: 9c765b1b3bda
Revises: 32c08c6c0e68
Create Date: 2026-09-05 17:25:57.091612

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c765b1b3bda"
down_revision: Union[str, None] = "32c08c6c0e68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default ajoute a la main : SQLite refuse une colonne NOT NULL sans
    # defaut cote base, et le `default=list` du modele est cote Python seulement.
    op.add_column(
        "data_sources",
        sa.Column("flux_decouverts", sa.JSON(), nullable=False, server_default="[]"),
    )
    op.add_column(
        "data_sources",
        sa.Column("flux_selectionnes", sa.JSON(), nullable=False, server_default="[]"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_sources", "flux_selectionnes")
    op.drop_column("data_sources", "flux_decouverts")
    # ### end Alembic commands ###
