"""budget, token breakdown and sync stats

Revision ID: b31d8041d874
Revises: 4f2a9c1d7e3b
Create Date: 2026-09-06 00:20:48.863424

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b31d8041d874"
down_revision: Union[str, None] = "4f2a9c1d7e3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_sources", sa.Column("lignes_synchronisees", sa.Integer(), nullable=True))
    op.add_column(
        "data_sources", sa.Column("derniere_sync_le", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("organizations", sa.Column("budget_mensuel_dollars", sa.Float(), nullable=True))
    op.add_column(
        "organizations",
        sa.Column("seuil_alerte_pct", sa.Integer(), server_default="80", nullable=False),
    )
    op.add_column(
        "organizations",
        sa.Column("budget_bloquant", sa.Boolean(), server_default=sa.text("1"), nullable=False),
    )
    op.add_column(
        "questions", sa.Column("jetons_entree", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "questions", sa.Column("jetons_sortie", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "questions", sa.Column("jetons_cache_lus", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "questions",
        sa.Column("jetons_cache_ecrits", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "jetons_cache_ecrits")
    op.drop_column("questions", "jetons_cache_lus")
    op.drop_column("questions", "jetons_sortie")
    op.drop_column("questions", "jetons_entree")
    op.drop_column("organizations", "budget_bloquant")
    op.drop_column("organizations", "seuil_alerte_pct")
    op.drop_column("organizations", "budget_mensuel_dollars")
    op.drop_column("data_sources", "derniere_sync_le")
    op.drop_column("data_sources", "lignes_synchronisees")
    # ### end Alembic commands ###
