"""add analyse and graphique to questions

Revision ID: c78c96e1c6f0
Revises: 0c025fb9ac96
Create Date: 2026-09-05 22:57:00.254658

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c78c96e1c6f0"
down_revision: Union[str, None] = "0c025fb9ac96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("analyse", sa.JSON(), nullable=True))
    op.add_column("questions", sa.Column("graphique", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "graphique")
    op.drop_column("questions", "analyse")
    # ### end Alembic commands ###
