"""jeton de partage des tableaux

Revision ID: ff3a066fe009
Revises: 53f07859dc37
Create Date: 2026-09-22 22:42:53.536555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3a066fe009'
down_revision: Union[str, None] = '53f07859dc37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('jeton_partage', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_dashboards_jeton_partage'), 'dashboards', ['jeton_partage'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboards_jeton_partage'), table_name='dashboards')
    op.drop_column('dashboards', 'jeton_partage')
    # ### end Alembic commands ###
